### ISSUE TITLE
Allow ctrl+<number> to change highlight color

### ISSUE THREAD

**Issue by ixera** [Timwi/KtaneContent#1327]
Hi,

Currently with my browser settings (Firefox on Linux w/ the Multi-Account Containers extension), alt+1-9 are bound to switching tabs (instead of ctrl+0-9 like on Windows), and ctrl+shift+1-9 to open a new tab in one of Multi-Account Containers' containers; neither have configurable modifier keys. Because of that, I can't comfortably switch highlight colors at all, so I'd like to suggest an option to switch from alt+1-9 to ctrl+1-9 for changing highlight colors. It's probably not worth changing alt+o, alt+c, etc. to ctrl, since those would conflict with much more universal browser shortcuts.

I'm mostly creating this issue to get thoughts from maintainers; I'm happy to take care of the implementation and send a pull request when done.

Thanks in advance!

**Comment by red031000** [comment]
solved (by yourself) in #1328
