### ISSUE TITLE
Custom logging for Minecraft Survival

### ISSUE THREAD

**Issue by rocket0634** [Timwi/KtaneContent#624]
Minecraft Survival is a long module that has logging for every action taken. I propose to condense this up a bit so that each part of the logging has their own section:
- Gathering
- Crafting
- Fighting
It'll make the log a lot easier to understand for users, and hopefully wouldn't result in a bunch of scrolling to see the entire thing.

**Comment by tandyCake** [comment]
I believe this issue is resolved as of commit `9dae8a`
