### ISSUE TITLE
Complicated Wires ruleseed code doesn't work

### ISSUE THREAD

**Issue by pedantic42** [Timwi/KtaneContent#663]
The ruleseed code for Complicated Wires.html is trying to getElementById('venn-ffff') and the like, but those IDs don't exist in the HTML so the page doesn't get updated with the new values.

**Comment by AndrioCelos** [comment]
It looks like 4b205b659632fd0790510174d41cafbcba5ffa58 broke it as the SVG compression process removed the IDs.
