### ISSUE TITLE
Add my new module

### ISSUE THREAD

**Issue by siky112** [Timwi/KtaneContent#702]
I made a module called Color Numbers, and I just released it so it should be put up on the repository.

**Comment by rocket0634** [comment]
Please make sure to send your HTML manual to us so we can upload it.
And if you have source code for the module, make sure to remember to upload the stuff in the Assets folder, as that consists of the actual module

**Comment by siky112** [comment]
the entire thing is at https://github.com/siky112/colorNumbers

**Comment by rocket0634** [comment]
The assets and the manual HTML are both missing, so unfortunately we can't do anything until the proper files are available.

**Comment by siky112** [comment]
ok deleting and recreating

**Comment by siky112** [comment]
ok did it

**Comment by rocket0634** [comment]
For future reference, are you only contactable on Steam and Github?
Do you have a Twitch or Discord contact?

**Comment by siky112** [comment]
i am only contactable on steam and github

**Comment by rocket0634** [comment]
Alright. If you change your mind, updates and information about the repo and twitch plays can be found on the ktane server of Discord.

**Comment by siky112** [comment]
can you just notify me on github? that seems easier

**Comment by siky112** [comment]
um, you guys working on it?

**Comment by siky112** [comment]
i mean, it can't take that long, can it?

**Comment by kavinkul** [comment]
Hi, do you have JSON file readily available for us?

**Comment by siky112** [comment]
what's a JSON file

**Comment by kavinkul** [comment]
It's the file that the website use to display the module along with some other information. It is also used by DBML in Tweaks mod. This is what it looks like for example:
```json
{
  "Author": "KingSlendy",
  "Compatibility": "Compatible",
  "DefuserDifficulty": "Hard",
  "Description": "Find 2 pairs of buttons hidden within a bunch of similar and colorful buttons to know which buttons are correct. Tags: 35-buttons, color, colour, pattern, colorful, colourful, pairs",
  "ExpertDifficulty": "Medium",
  "ModuleID": "ColorfulInsanity",
  "Name": "Colorful Insanity",
  "Origin": "Mods",
  "Published": "2019-01-29",
  "RuleSeedSupport": "Supported",
  "SortKey": "COLORFULINSANITY",
  "SourceUrl": "https://github.com/KingSlendy/ktanecolorfulinsanity",
  "Souvenir": { "Status": "NotACandidate" },
  "SteamID": "1639334945",
  "Symbol": "Coi",
  "TutorialVideoUrl": "https://www.youtube.com/watch?v=5C8S6g4FovU",
  "Type": "Regular"
}
```

**Comment by kavinkul** [comment]
If you go to the website, then go to tools > Create new module, you can generate the json there.

**Comment by siky112** [comment]
Ok, lemme generate that now

Btw, my module has many things to fix if you're willing to help.

**Comment by kavinkul** [comment]
For adding colorblind mode and Twitch Plays, it's not really our job to add them for you. I will forward your request to the modders in discord server if any of them want to add those features to your module.
We do write the manual in html format for you if you don't know html at all, but I encourage every modder to try and learn html. It's not too difficult and I think the template manual explain the basic well enough to write simple manuals. Sometimes it can be tricky to get the manual look in the way you want. You may want to ask us in that case.
You can request any contributor to create svg for you. If you want to do that by yourself, I would suggest using inkscape as it is free. In any case, I have created html and svg for this module so you don't have to do that.

**Comment by siky112** [comment]
Here you go

`{
  "Author": "R3Ked",
  "Compatibility": "Compatible",
  "DefuserDifficulty": "VeryEasy",
  "Description": "Press the button with the correct number on it based on an LED in the center. Tags: one, two, three, four, led",
  "ExpertDifficulty": "VeryEasy",
  "ModuleID": "colorNumbers",
  "Name": "Color Numbers",
  "Origin": "Mods",
  "Published": "2020-07-12",
  "RuleSeedSupport": "Supported",
  "SortKey": "COLORNUMBERS",
  "SourceUrl": "https://github.com/siky112/colorNumbers",
  "SteamID": "2164083287",
  "Symbol": "Cnu",
  "Type": "Regular"
}`

**Comment by siky112** [comment]
Also, I do not see any pull requests so I cannot put use the SVG file you made.

**Comment by kavinkul** [comment]
I can submit a PR to add both html and svg to your source code if you wish, but I will use the html and svg for the manual anyway so you shouldn't have to worry about formatting them or anything.

**Comment by siky112** [comment]
ok
