### ISSUE TITLE
Add my newer module

### ISSUE THREAD

**Issue by siky112** [Timwi/KtaneContent#710]
I'm throwing another brick at your window and giving you another module to add.

The JSON you need

`{
  "Author": "R3Ked",
  "Compatibility": "Compatible",
  "DefuserDifficulty": "VeryEasy",
  "Description": "Press the button with the correct number on it based on two LEDs. Tags: one, two, two-buttons, two-leds",
  "ExpertDifficulty": "Easy",
  "ModuleID": "colorOneTwo",
  "Name": "Color One Two",
  "Origin": "Mods",
  "Published": "2020-07-25",
  "SortKey": "COLORONETWO",
  "SourceUrl": "https://github.com/siky112/ColorOneTwo",
  "SteamID": "2177850675",
  "Symbol": "Clot",
  "Type": "Regular"
}`

Git repo at https://github.com/siky112/ColorOneTwo

i am so tired and it's only 4 pm

**Comment by siky112** [comment]
me being tired isn't the module's fault by the way i had to do lots of stuff today

**Comment by siky112** [comment]
Oh yeah, you need the name. Color One Two.

**Comment by siky112** [comment]
Hello?

**Comment by kavinkul** [comment]
We are currently having a backlog of requests and not many contributors available to take them at the moment. That said, I'll be taking your request.
